name: onewaytosite_app
description: "A secure password vault app built in 2026."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # ไอคอนพื้นฐาน
  cupertino_icons: ^1.0.8
  
  # ระบบบันทึกข้อมูลลงเครื่องถาวร (เพิ่มตัวนี้)
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  # เปิดใช้งาน Material Design 3
  uses-material-design: true

  # หากต้องการเพิ่มรูปภาพในอนาคต ให้เอาเครื่องหมาย # ออกหน้า assets:
  # assets:
  #   - assets/images/logo.png